export const ActionTypes = {
  STORE_ZIP_DATA: 'STORE_ZIP_DATA',
  STORE_TEXT_DATA: 'STORE_TEXT_DATA',
  DATA_LIST: 'DATA_LIST',
  FILE_INFO: 'FILE_INFO',
  PARSED_DATA: 'PARSED_DATA',

  LOG: 'LOG',
  DELETE_LOG: 'DELETE_LOG'
};
